/**
 * Playwright TypeScript Exporter.
 *
 * Generates a strictly-typed TypeScript Playwright script with an
 * interface for all parameterized workflow variables.
 */

import type { Workflow, WorkflowStep } from '@shared/types';
import { slugify } from '@shared/utils';

function getSelector(step: WorkflowStep): string {
  if ('target' in step && step.target?.selectors && step.target.selectors.length > 0) {
    const primary = step.target.selectors[0]!;
    if (primary.type === 'xpath') {
      return `xpath=${primary.value}`;
    }
    return primary.value;
  }
  return 'body';
}

function formatValue(val: string): string {
  const match = val.match(/^\{\{([a-zA-Z0-9_]+)\}\}$/);
  if (match) {
    return `vars.${match[1]}`;
  }
  if (val.includes('{{')) {
    const templated = val.replace(/\{\{([a-zA-Z0-9_]+)\}\}/g, '${vars.$1}');
    return `\`${templated}\``;
  }
  return JSON.stringify(val);
}

function mapVariableType(type: string): string {
  switch (type) {
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    default:
      return 'string';
  }
}

export function exportToPlaywrightTS(workflow: Workflow): { content: string; filename: string; mimeType: string } {
  const lines: string[] = [];

  lines.push('// Auto-generated by Workflow Recorder');
  lines.push(`// Workflow: ${workflow.name}`);
  lines.push('import { chromium, Browser, BrowserContext, Page } from "playwright";');
  lines.push('');

  // Interface for variables
  lines.push('export interface WorkflowVariables {');
  if (workflow.variables.length === 0) {
    lines.push('  [key: string]: string | number | boolean | undefined;');
  } else {
    workflow.variables.forEach((v) => {
      const opt = v.required ? '' : '?';
      lines.push(`  ${v.name}${opt}: ${mapVariableType(v.type)};`);
    });
  }
  lines.push('}');
  lines.push('');

  // Default variables
  lines.push('const defaultVariables: WorkflowVariables = {');
  workflow.variables.forEach((v) => {
    const defaultVal = v.defaultValue !== undefined ? JSON.stringify(v.defaultValue) : '""';
    lines.push(`  ${v.name}: ${defaultVal},`);
  });
  lines.push('};');
  lines.push('');

  lines.push('export async function runWorkflow(customVars: Partial<WorkflowVariables> = {}): Promise<void> {');
  lines.push('  const vars: WorkflowVariables = { ...defaultVariables, ...customVars };');
  lines.push('  const browser: Browser = await chromium.launch({ headless: false });');
  lines.push('  const context: BrowserContext = await browser.newContext();');
  lines.push('  const page: Page = await context.newPage();');
  lines.push(`  page.setDefaultTimeout(${workflow.settings.defaultTimeout || 15000});`);
  lines.push('');

  workflow.steps.forEach((step, idx) => {
    if (step.disabled) {
      lines.push(`  // Step ${idx + 1}: ${step.description || step.type} [DISABLED]`);
      return;
    }

    lines.push(`  // Step ${idx + 1}: ${step.description || step.type}`);
    const sel = getSelector(step);

    switch (step.type) {
      case 'navigate':
        lines.push(`  await page.goto(${formatValue(step.url)});`);
        break;
      case 'click':
        if (step.clickType === 'double') {
          lines.push(`  await page.locator(${JSON.stringify(sel)}).dblclick();`);
        } else if (step.clickType === 'right') {
          lines.push(`  await page.locator(${JSON.stringify(sel)}).click({ button: "right" });`);
        } else {
          lines.push(`  await page.locator(${JSON.stringify(sel)}).click();`);
        }
        break;
      case 'input':
        lines.push(`  await page.locator(${JSON.stringify(sel)}).fill(String(${formatValue(step.value)}));`);
        break;
      case 'select':
        lines.push(`  await page.locator(${JSON.stringify(sel)}).selectOption(String(${formatValue(step.value)}));`);
        break;
      case 'checkbox':
        lines.push(`  await page.locator(${JSON.stringify(sel)}).setChecked(${step.checked});`);
        break;
      case 'radio':
        lines.push(`  await page.locator(${JSON.stringify(sel)}).check();`);
        break;
      case 'hover':
        lines.push(`  await page.locator(${JSON.stringify(sel)}).hover();`);
        break;
      case 'keyPress':
        lines.push(`  await page.keyboard.press(${JSON.stringify(step.key)});`);
        break;
      case 'scroll':
        lines.push(`  await page.evaluate(({ x, y }: { x: number; y: number }) => window.scrollTo(x, y), { x: ${step.position.x}, y: ${step.position.y} });`);
        break;
      case 'wait':
        lines.push(`  await page.waitForTimeout(${step.timeout || 1000});`);
        break;
      case 'waitForElement':
        lines.push(`  await page.locator(${JSON.stringify(sel)}).waitFor({ state: "attached" });`);
        break;
      case 'waitForVisible':
        lines.push(`  await page.locator(${JSON.stringify(sel)}).waitFor({ state: "visible" });`);
        break;
      case 'assert':
        if (step.assertion.operator === 'contains') {
          lines.push(`  const text_${idx} = await page.locator(${JSON.stringify(sel)}).innerText();`);
          lines.push(`  if (!text_${idx}.includes(${JSON.stringify(step.assertion.expected)})) throw new Error("Assertion failed: Expected text not found");`);
        } else if (step.assertion.operator === 'visible') {
          lines.push(`  await page.locator(${JSON.stringify(sel)}).waitFor({ state: "visible" });`);
        }
        break;
      default:
        break;
    }

    lines.push('');
  });

  lines.push('  await context.close();');
  lines.push('  await browser.close();');
  lines.push('}');

  const content = lines.join('\n');
  const slug = slugify(workflow.name) || 'workflow';

  return {
    content,
    filename: `${slug}.playwright.ts`,
    mimeType: 'application/typescript',
  };
}
