/**
 * Puppeteer JavaScript Exporter.
 *
 * Generates an executable Puppeteer script.
 */

import type { Workflow, WorkflowStep } from '@shared/types';
import { slugify } from '@shared/utils';

function getSelector(step: WorkflowStep): string {
  if ('target' in step && step.target?.selectors && step.target.selectors.length > 0) {
    const primary = step.target.selectors[0]!;
    return primary.value;
  }
  return 'body';
}

function formatValue(val: string): string {
  const match = val.match(/^\{\{([a-zA-Z0-9_]+)\}\}$/);
  if (match) {
    return `vars.${match[1]}`;
  }
  if (val.includes('{{')) {
    const templated = val.replace(/\{\{([a-zA-Z0-9_]+)\}\}/g, '${vars.$1}');
    return `\`${templated}\``;
  }
  return JSON.stringify(val);
}

export function exportToPuppeteer(workflow: Workflow): { content: string; filename: string; mimeType: string } {
  const lines: string[] = [];

  lines.push('// Auto-generated by Workflow Recorder');
  lines.push(`// Workflow: ${workflow.name}`);
  lines.push('import puppeteer from "puppeteer";');
  lines.push('');

  lines.push('const defaultVariables = {');
  workflow.variables.forEach((v) => {
    const defaultVal = v.defaultValue !== undefined ? JSON.stringify(v.defaultValue) : '""';
    lines.push(`  ${v.name}: ${defaultVal},`);
  });
  lines.push('};');
  lines.push('');

  lines.push('export async function runWorkflow(customVars = {}) {');
  lines.push('  const vars = { ...defaultVariables, ...customVars };');
  lines.push('  const browser = await puppeteer.launch({ headless: false, defaultViewport: null });');
  lines.push('  const page = await browser.newPage();');
  lines.push(`  page.setDefaultTimeout(${workflow.settings.defaultTimeout || 15000});`);
  lines.push('');

  workflow.steps.forEach((step, idx) => {
    if (step.disabled) {
      lines.push(`  // Step ${idx + 1}: ${step.description || step.type} [DISABLED]`);
      return;
    }

    lines.push(`  // Step ${idx + 1}: ${step.description || step.type}`);
    const sel = getSelector(step);

    switch (step.type) {
      case 'navigate':
        lines.push(`  await page.goto(${formatValue(step.url)}, { waitUntil: "networkidle2" });`);
        break;
      case 'click':
        lines.push(`  await page.waitForSelector(${JSON.stringify(sel)});`);
        if (step.clickType === 'double') {
          lines.push(`  await page.click(${JSON.stringify(sel)}, { clickCount: 2 });`);
        } else if (step.clickType === 'right') {
          lines.push(`  await page.click(${JSON.stringify(sel)}, { button: "right" });`);
        } else {
          lines.push(`  await page.click(${JSON.stringify(sel)});`);
        }
        break;
      case 'input':
        lines.push(`  await page.waitForSelector(${JSON.stringify(sel)});`);
        lines.push(`  await page.click(${JSON.stringify(sel)}, { clickCount: 3 });`);
        lines.push(`  await page.type(${JSON.stringify(sel)}, String(${formatValue(step.value)}));`);
        break;
      case 'select':
        lines.push(`  await page.waitForSelector(${JSON.stringify(sel)});`);
        lines.push(`  await page.select(${JSON.stringify(sel)}, String(${formatValue(step.value)}));`);
        break;
      case 'checkbox':
      case 'radio':
        lines.push(`  await page.waitForSelector(${JSON.stringify(sel)});`);
        lines.push(`  await page.click(${JSON.stringify(sel)});`);
        break;
      case 'hover':
        lines.push(`  await page.waitForSelector(${JSON.stringify(sel)});`);
        lines.push(`  await page.hover(${JSON.stringify(sel)});`);
        break;
      case 'keyPress':
        lines.push(`  await page.keyboard.press(${JSON.stringify(step.key)});`);
        break;
      case 'scroll':
        lines.push(`  await page.evaluate(({ x, y }) => window.scrollTo(x, y), { x: ${step.position.x}, y: ${step.position.y} });`);
        break;
      case 'wait':
        lines.push(`  await new Promise(r => setTimeout(r, ${step.timeout || 1000}));`);
        break;
      case 'waitForElement':
      case 'waitForVisible':
        lines.push(`  await page.waitForSelector(${JSON.stringify(sel)}, { visible: true });`);
        break;
      case 'assert':
        lines.push(`  await page.waitForSelector(${JSON.stringify(sel)});`);
        break;
      default:
        break;
    }

    lines.push('');
  });

  lines.push('  await browser.close();');
  lines.push('}');

  const content = lines.join('\n');
  const slug = slugify(workflow.name) || 'workflow';

  return {
    content,
    filename: `${slug}.puppeteer.js`,
    mimeType: 'application/javascript',
  };
}
