/**
 * Selenium Python Exporter.
 *
 * Generates an idiomatic, executable Python script using selenium.webdriver.
 */

import type { Workflow, WorkflowStep } from '@shared/types';
import { slugify } from '@shared/utils';

function getSeleniumLocator(step: WorkflowStep): { by: string; value: string } {
  if ('target' in step && step.target?.selectors && step.target.selectors.length > 0) {
    const primary = step.target.selectors[0]!;
    if (primary.type === 'xpath' || primary.value.startsWith('//') || primary.value.startsWith('(')) {
      return { by: 'By.XPATH', value: primary.value };
    }
    if (primary.type === 'id' || (primary.value.startsWith('#') && !primary.value.includes(' ') && !primary.value.includes('>'))) {
      return { by: 'By.ID', value: primary.value.replace(/^#/, '') };
    }
    if (primary.type === 'name') {
      return { by: 'By.NAME', value: primary.value };
    }
    return { by: 'By.CSS_SELECTOR', value: primary.value };
  }
  return { by: 'By.TAG_NAME', value: 'body' };
}

function formatPythonValue(val: string): string {
  const match = val.match(/^\{\{([a-zA-Z0-9_]+)\}\}$/);
  if (match) {
    return `vars["${match[1]}"]`;
  }
  if (val.includes('{{')) {
    const templated = val.replace(/\{\{([a-zA-Z0-9_]+)\}\}/g, '{vars["$1"]}');
    return `f"${templated}"`;
  }
  return JSON.stringify(val);
}

export function exportToSeleniumPython(workflow: Workflow): { content: string; filename: string; mimeType: string } {
  const lines: string[] = [];

  lines.push('#!/usr/bin/env python3');
  lines.push('# Auto-generated by Workflow Recorder');
  lines.push(`# Workflow: ${workflow.name}`);
  lines.push('import time');
  lines.push('from selenium import webdriver');
  lines.push('from selenium.webdriver.common.by import By');
  lines.push('from selenium.webdriver.common.keys import Keys');
  lines.push('from selenium.webdriver.support.ui import WebDriverWait');
  lines.push('from selenium.webdriver.support import expected_conditions as EC');
  lines.push('from selenium.webdriver.common.action_chains import ActionChains');
  lines.push('');

  lines.push('DEFAULT_VARIABLES = {');
  workflow.variables.forEach((v) => {
    const defVal = v.defaultValue !== undefined ? JSON.stringify(v.defaultValue) : '""';
    lines.push(`    "${v.name}": ${defVal},`);
  });
  lines.push('}');
  lines.push('');

  lines.push('def run_workflow(custom_vars=None):');
  lines.push('    vars = {**DEFAULT_VARIABLES, **(custom_vars or {})}');
  lines.push('    options = webdriver.ChromeOptions()');
  lines.push('    driver = webdriver.Chrome(options=options)');
  const timeoutSec = Math.round((workflow.settings.defaultTimeout || 15000) / 1000);
  lines.push(`    wait = WebDriverWait(driver, ${timeoutSec})`);
  lines.push('    actions = ActionChains(driver)');
  lines.push('    try:');

  workflow.steps.forEach((step, idx) => {
    if (step.disabled) {
      lines.push(`        # Step ${idx + 1}: ${step.description || step.type} [DISABLED]`);
      return;
    }

    lines.push(`        # Step ${idx + 1}: ${step.description || step.type}`);
    const { by, value } = getSeleniumLocator(step);

    switch (step.type) {
      case 'navigate':
        lines.push(`        driver.get(${formatPythonValue(step.url)})`);
        break;
      case 'click':
        lines.push(`        elem_${idx} = wait.until(EC.element_to_be_clickable((${by}, ${JSON.stringify(value)})))`);
        if (step.clickType === 'double') {
          lines.push(`        actions.double_click(elem_${idx}).perform()`);
        } else if (step.clickType === 'right') {
          lines.push(`        actions.context_click(elem_${idx}).perform()`);
        } else {
          lines.push(`        elem_${idx}.click()`);
        }
        break;
      case 'input':
        lines.push(`        elem_${idx} = wait.until(EC.visibility_of_element_located((${by}, ${JSON.stringify(value)})))`);
        lines.push(`        elem_${idx}.clear()`);
        lines.push(`        elem_${idx}.send_keys(str(${formatPythonValue(step.value)}))`);
        break;
      case 'select':
        lines.push(`        elem_${idx} = wait.until(EC.visibility_of_element_located((${by}, ${JSON.stringify(value)})))`);
        lines.push(`        elem_${idx}.send_keys(str(${formatPythonValue(step.value)}))`);
        break;
      case 'checkbox':
        lines.push(`        elem_${idx} = wait.until(EC.element_to_be_clickable((${by}, ${JSON.stringify(value)})))`);
        lines.push(`        if elem_${idx}.is_selected() != ${step.checked ? 'True' : 'False'}:`);
        lines.push(`            elem_${idx}.click()`);
        break;
      case 'radio':
        lines.push(`        elem_${idx} = wait.until(EC.element_to_be_clickable((${by}, ${JSON.stringify(value)})))`);
        lines.push(`        elem_${idx}.click()`);
        break;
      case 'hover':
        lines.push(`        elem_${idx} = wait.until(EC.visibility_of_element_located((${by}, ${JSON.stringify(value)})))`);
        lines.push(`        actions.move_to_element(elem_${idx}).perform()`);
        break;
      case 'keyPress':
        lines.push(`        actions.send_keys(Keys.RETURN).perform() if ${JSON.stringify(step.key)} == "Enter" else actions.send_keys(${JSON.stringify(step.key)}).perform()`);
        break;
      case 'scroll':
        lines.push(`        driver.execute_script("window.scrollTo(arguments[0], arguments[1]);", ${step.position.x}, ${step.position.y})`);
        break;
      case 'wait':
        lines.push(`        time.sleep(${Math.max((step.timeout || 1000) / 1000, 0.1)})`);
        break;
      case 'waitForElement':
      case 'waitForVisible':
        lines.push(`        wait.until(EC.visibility_of_element_located((${by}, ${JSON.stringify(value)})))`);
        break;
      case 'assert':
        lines.push(`        elem_${idx} = wait.until(EC.visibility_of_element_located((${by}, ${JSON.stringify(value)})))`);
        if (step.assertion.operator === 'contains') {
          lines.push(`        assert ${JSON.stringify(step.assertion.expected)} in elem_${idx}.text, "Assertion failed"`);
        }
        break;
      default:
        break;
    }

    lines.push('');
  });

  lines.push('    finally:');
  lines.push('        driver.quit()');
  lines.push('');
  lines.push('if __name__ == "__main__":');
  lines.push('    run_workflow()');

  const content = lines.join('\n');
  const slug = slugify(workflow.name) || 'workflow';

  return {
    content,
    filename: `${slug}.selenium.py`,
    mimeType: 'text/x-python',
  };
}
